services:
  - type: web
    name: tictactoe-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python tictactoe_bot.py
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token
      - key: WEBHOOK_URL
        value: https://your-render-url.onrender.com
